# Generated by Django 6.0.7 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_amount_subscription_is_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Paid', 'Paid'),
                    ('Failed', 'Failed'),
                    ('Refunded', 'Refunded'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
    ]