# Generated by Django 6.0.7 on 2026-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='employees',
            field=models.PositiveIntegerField(default=0, help_text="Legacaly/manual snapshot field — no longer used for display. The Employees column is now computed live from the organization's active employees (see live_employee_count() below), since org admins add/remove employees after a subscription is created and this stored value was never kept in sync."),
        ),
    ]
