# Generated by Django 4.2.7 on 2026-08-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        # Already creating the correct table name in 0001_initial,
        # so this migration is now a no-op.
    ]
