# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(db_column='NotificationId', primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee')], db_column='RecipientType', max_length=20)),
                ('notification_type', models.CharField(choices=[('Appointment Confirmation', 'Appointment Confirmation'), ('Appointment Status Update', 'Appointment Status Update'), ('Appointment Reminder', 'Appointment Reminder'), ('General', 'General')], db_column='NotificationType', default='General', max_length=50)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('message', models.TextField(db_column='Message')),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('created_on', models.DateTimeField(db_column='CreatedOn', default=django.utils.timezone.now)),
                ('read_on', models.DateTimeField(blank=True, db_column='ReadOn', null=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='AppointmentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
                ('employee', models.ForeignKey(blank=True, db_column='EmployeeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
                ('org', models.ForeignKey(blank=True, db_column='OrgId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['recipient_type'], name='Notificatio_Recipie_d81f75_idx'), models.Index(fields=['customer'], name='Notificatio_Custome_9fae8c_idx'), models.Index(fields=['employee'], name='Notificatio_Employe_02cdf2_idx'), models.Index(fields=['is_read'], name='Notificatio_IsRead_4e7907_idx'), models.Index(fields=['org'], name='Notificatio_OrgId_9d4dbd_idx')],
            },
        ),
    ]
