# Generated by Django 6.0.7 on 2026-08-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Appointment Confirmation', 'Appointment Confirmation'), ('Appointment Status Update', 'Appointment Status Update'), ('Appointment Reminder', 'Appointment Reminder'), ('Organization Registration', 'Organization Registration'), ('Organization Status Update', 'Organization Status Update'), ('General', 'General')], db_column='NotificationType', default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Organization', 'Organization')], db_column='RecipientType', max_length=20),
        ),
    ]
