# Generated by Django 6.0.7 on 2026-08-11 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmentservice_status'),
        ('customers', '0001_initial'),
        ('employees', '0004_grandfather_existing_employees_password'),
        ('notifications', '0002_alter_notification_notification_type_and_more'),
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, db_column='RecipientUserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Organization', 'Organization'), ('OrganizationAdmin', 'Organization Admin')], db_column='RecipientType', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user'], name='Notificatio_Recipie_e2be9a_idx'),
        ),
    ]
