# Generated by Django 6.0.7 on 2026-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_recipient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Appointment Confirmation', 'Appointment Confirmation'), ('Appointment Status Update', 'Appointment Status Update'), ('Appointment Reminder', 'Appointment Reminder'), ('Organization Registration', 'Organization Registration'), ('Organization Status Update', 'Organization Status Update'), ('Feedback Received', 'Feedback Received'), ('General', 'General')], db_column='NotificationType', default='General', max_length=50),
        ),
    ]
