# Generated by Django 6.0.7 on 2026-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_Recipie_1b8ce1_idx',
            old_name='Notificatio_Recipie_d81f75_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_Custome_3e035d_idx',
            old_name='Notificatio_Custome_9fae8c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_Employe_f1f0b3_idx',
            old_name='Notificatio_Employe_02cdf2_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_Recipie_6e7417_idx',
            old_name='Notificatio_Recipie_e2be9a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_IsRead_a5e426_idx',
            old_name='Notificatio_IsRead_4e7907_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_OrgId_19a2b8_idx',
            old_name='Notificatio_OrgId_9d4dbd_idx',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
