# Generated by Django 6.0.7 on 2026-07-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['plan_name']},
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
    ]
