# Generated by Django 6.0.7 on 2026-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_options_alter_plan_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['monthly_price']},
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of {"label": str, "included": bool} objects, e.g. [{"label": "Email support", "included": true}]'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for a paid plan. Set to mark this as a free trial.', null=True),
        ),
    ]
