# Generated by Django 6.0.7 on 2026-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name']},
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
