# Generated by Django 6.1 on 2026-08-21 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0008_remove_appointment_started_at_and_more'),
        ('customers', '0001_initial'),
        ('employees', '0009_remove_employee_is_paused'),
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(db_column='FeedbackId', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='Rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('appointment', models.ForeignKey(db_column='AppointmentId', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='appointments.appointment')),
                ('appointment_service', models.OneToOneField(db_column='AppointmentServiceId', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments.appointmentservice')),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='customers.customer')),
                ('employee', models.ForeignKey(blank=True, db_column='EmployeeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='employees.employee')),
                ('org', models.ForeignKey(blank=True, db_column='OrgId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='organizations.organization')),
            ],
            options={
                'db_table': 'Feedback',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['employee'], name='Feedback_Employe_ecedfe_idx'), models.Index(fields=['appointment'], name='Feedback_Appoint_91eaa4_idx'), models.Index(fields=['org'], name='Feedback_OrgId_4e2e73_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('feedback_request_id', models.AutoField(db_column='FeedbackRequestId', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='Token', db_index=True, max_length=64, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('expires_on', models.DateTimeField(db_column='ExpiresOn')),
                ('is_submitted', models.BooleanField(db_column='IsSubmitted', default=False)),
                ('submitted_on', models.DateTimeField(blank=True, db_column='SubmittedOn', null=True)),
                ('appointment', models.OneToOneField(db_column='AppointmentId', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='appointments.appointment')),
            ],
            options={
                'db_table': 'FeedbackRequest',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['token'], name='FeedbackReq_Token_03edb4_idx'), models.Index(fields=['appointment'], name='FeedbackReq_Appoint_63db44_idx')],
            },
        ),
    ]
