# Generated by Django 6.0.7 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointmentservice_waiting_time_min_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='appointment_service',
            field=models.OneToOneField(blank=True, db_column='AppointmentServiceId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='appointments.appointmentservice'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='appointment',
            field=models.ForeignKey(db_column='AppointmentId', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='appointments.appointment'),
        ),
    ]
