# Generated by Django 6.0.7 on 2026-09-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackrequest_appointment_service'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedbackreq_Token_39229d_idx',
            old_name='FeedbackReq_Token_03edb4_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedbackreq_Appoint_417300_idx',
            old_name='FeedbackReq_Appoint_63db44_idx',
        ),
        migrations.AlterModelTable(
            name='feedbackrequest',
            table='feedbackrequest',
        ),
    ]
