# Generated by Django 6.0.7 on 2026-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(db_column='AppointmentId', primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(db_column='AppointmentNumber', db_index=True, max_length=20, unique=True)),
                ('token_number', models.CharField(db_column='TokenNumber', db_index=True, max_length=20)),
                ('date', models.DateField(db_column='AppointmentDate', db_index=True)),
                ('time', models.TimeField(db_column='AppointmentTime')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Left Queue', 'Left Queue')], db_column='Status', db_index=True, default='Confirmed', max_length=20)),
                ('total_fee', models.DecimalField(db_column='TotalFee', decimal_places=2, default=0, max_digits=10)),
                ('total_duration_min', models.PositiveIntegerField(db_column='TotalDurationMin', default=0)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'db_table': 'Appointment',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('appointment_service_id', models.AutoField(db_column='AppointmentServiceId', primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column='ServiceName', max_length=255)),
                ('duration_min', models.PositiveIntegerField(db_column='DurationMin', default=0)),
                ('fee', models.DecimalField(db_column='Fee', decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='Status', default='Confirmed', max_length=20)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'db_table': 'AppointmentService',
                'ordering': ['appointment_service_id'],
            },
        ),
    ]
