# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='org',
            field=models.ForeignKey(blank=True, db_column='OrgId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(db_column='AppointmentId', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointments.appointment'),
        ),
    ]
