# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='EmployeeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_services', to='employees.employee'),
        ),
    ]
