# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.PROTECT, related_name='appointment_services', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_number'], name='Appointment_Appoint_6000dc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['token_number'], name='Appointment_TokenNu_e13c40_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='Appointment_Appoint_69b59e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='Appointment_Status_2acdbf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['org'], name='Appointment_OrgId_fb5573_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('org', 'date', 'token_number')},
        ),
        migrations.AddIndex(
            model_name='appointmentservice',
            index=models.Index(fields=['appointment'], name='Appointment_Appoint_39109d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentservice',
            index=models.Index(fields=['service'], name='Appointment_Service_182905_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentservice',
            index=models.Index(fields=['employee'], name='Appointment_Employe_4885f7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentservice',
            index=models.Index(fields=['status'], name='Appointment_Status_8b0d2b_idx'),
        ),
    ]
