# Generated by Django 6.0.7 on 2026-08-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, db_column='StartedAt', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Left Queue', 'Left Queue'), ('Rescheduled', 'Rescheduled')], db_column='Status', db_index=True, default='Confirmed', max_length=20),
        ),
    ]
