# Generated by Django 6.0.7 on 2026-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_started_at_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Left Queue', 'Left Queue'), ('Rescheduled', 'Rescheduled')], db_column='Status', default='Confirmed', max_length=20),
        ),
    ]
