# Generated by Django 6.0.7 on 2026-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmentservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='actual_duration_min',
            field=models.PositiveIntegerField(blank=True, db_column='ActualDurationMin', null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='CompletedAt', null=True),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='started_at',
            field=models.DateTimeField(blank=True, db_column='StartedAt', null=True),
        ),
    ]
