# Generated by Django 6.0.7 on 2026-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointmentservice_actual_duration_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Left Queue', 'Left Queue')], db_column='Status', db_index=True, default='Confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Left Queue', 'Left Queue')], db_column='Status', default='Confirmed', max_length=20),
        ),
    ]
