# Generated by Django 6.0.7 on 2026-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='waiting_time_min',
            field=models.PositiveIntegerField(blank=True, db_column='WaitingTimeMin', null=True),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Left Queue', 'Left Queue')], db_column='Status', default='Confirmed', max_length=20),
        ),
    ]
