# Generated by Django 6.0.7 on 2026-09-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointmentservice_waiting_time_min_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_Appoint_3ba41b_idx',
            old_name='Appointment_Appoint_6000dc_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_TokenNu_e5022f_idx',
            old_name='Appointment_TokenNu_e13c40_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_Appoint_0139c0_idx',
            old_name='Appointment_Appoint_69b59e_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_Status_9d862b_idx',
            old_name='Appointment_Status_2acdbf_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_OrgId_5236ec_idx',
            old_name='Appointment_OrgId_fb5573_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_Appoint_4154f6_idx',
            old_name='Appointment_Appoint_39109d_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_Service_2887cd_idx',
            old_name='Appointment_Service_182905_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_Employe_427c0a_idx',
            old_name='Appointment_Employe_4885f7_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_Status_6ba950_idx',
            old_name='Appointment_Status_8b0d2b_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='appointmentservice',
            table='appointmentservice',
        ),
    ]
