# Generated by Django 6.0.7 on 2026-08-14 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_probability', models.FloatField(help_text='Probability of customer arrival per time unit (0.0 - 1.0)')),
                ('service_probability', models.FloatField(help_text='Probability of serving a customer per time unit (0.0 - 1.0)')),
                ('number_of_arrivals', models.PositiveIntegerField(help_text='Simulated number of customer arrivals')),
                ('time_horizon', models.PositiveIntegerField(help_text='Simulation time horizon in hours')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='organizations.organization')),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('customers_served', models.PositiveIntegerField(default=0)),
                ('currently_waiting', models.PositiveIntegerField(default=0)),
                ('left_without_service', models.PositiveIntegerField(default=0)),
                ('average_waiting_time', models.FloatField(default=0.0)),
                ('maximum_waiting_time', models.FloatField(default=0.0)),
                ('idle_time', models.FloatField(default=0.0)),
                ('utilization', models.FloatField(default=0.0, help_text='Utilization percentage 0-100')),
                ('recommended_doctors', models.PositiveIntegerField(default=1)),
                ('recommendation_message', models.CharField(default='', max_length=255)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='simulation.simulation')),
            ],
            options={
                'db_table': 'simulation_results',
            },
        ),
        migrations.CreateModel(
            name='SimulationTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField()),
                ('average_wait', models.FloatField(default=0.0)),
                ('maximum_queue', models.PositiveIntegerField(default=0)),
                ('utilization', models.FloatField(default=0.0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='simulation.simulation')),
            ],
            options={
                'db_table': 'simulation_trends',
                'ordering': ['hour'],
            },
        ),
    ]
