# Generated by Django 4.2.7 on 2026-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='recommendation_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
