# Generated by Django 4.2.7 on 2026-08-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
        ('simulation', '0002_alter_simulationresult_recommendation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='organizations.organization'),
        ),
    ]
