# Generated by Django 6.0.7 on 2026-07-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('action_name', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Export', 'Export'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('Assign', 'Assign'), ('Status Change', 'Status Change')], max_length=30)),
                ('action_screen', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Organization Admin', 'Organization Admin'), ('Employee', 'Employee')], max_length=30)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-audit_date'],
            },
        ),
    ]
