# Generated by Django 6.0.7 on 2026-08-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_name',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Export', 'Export'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('Assign', 'Assign'), ('Status Change', 'Status Change'), ('View', 'View')], max_length=30),
        ),
    ]
