# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_type_id', models.AutoField(db_column='ServiceTypeId', primary_key=True, serialize=False)),
                ('service_type_name', models.CharField(db_column='ServiceTypeName', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='Status', default='Active', max_length=10)),
                ('created_by', models.CharField(db_column='CreatedBy', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(db_column='UpdatedBy', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('organization', models.ForeignKey(blank=True, db_column='OrganizationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='organizations.organization')),
            ],
            options={
                'db_table': 'service_types',
                'ordering': ['service_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(db_column='ServiceId', primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column='ServiceName', max_length=150)),
                ('duration', models.PositiveIntegerField(db_column='Duration', help_text='Duration in minutes')),
                ('fee', models.DecimalField(db_column='Fee', decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='Status', default='Active', max_length=10)),
                ('created_by', models.CharField(db_column='CreatedBy', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(db_column='UpdatedBy', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('organization', models.ForeignKey(blank=True, db_column='OrganizationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization')),
                ('service_type', models.ForeignKey(db_column='ServiceTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicetype')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['service_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('organization', 'service_type_name'), name='unique_service_type_per_org'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'service_name'), name='unique_service_per_org'),
        ),
    ]
