# Generated by Django 6.0.7 on 2026-08-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicetype_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicetype',
            name='unique_service_type_per_category',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='category',
        ),
    ]
