# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(db_column='ShiftId', primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, db_column='CategoryId', db_index=True, null=True)),
                ('shift_name', models.CharField(db_column='ShiftName', max_length=100)),
                ('start_time', models.TimeField(db_column='StartTime')),
                ('end_time', models.TimeField(db_column='EndTime')),
                ('duration_hours', models.IntegerField(db_column='DurationHours', default=8)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='Status', default='Active', max_length=20)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
            ],
            options={
                'db_table': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_column='EmployeeCode', max_length=50, unique=True)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('employee_name', models.CharField(db_column='EmployeeName', max_length=255)),
                ('designation', models.CharField(db_column='Designation', max_length=255)),
                ('mobile', models.CharField(db_column='Mobile', max_length=15)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Hold', 'On Hold')], db_column='Status', default='Active', max_length=20)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('org', models.ForeignKey(blank=True, db_column='OrgId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('employee_service_id', models.AutoField(db_column='EmployeeServiceId', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='Status', default='Active', max_length=20)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='UpdatedOn')),
                ('employee', models.ForeignKey(db_column='EmployeeId', on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='employees.employee')),
            ],
            options={
                'db_table': 'EmployeeServices',
            },
        ),
    ]
