# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, db_column='ShiftId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservice',
            unique_together={('employee', 'service')},
        ),
    ]
