# Generated by Django 6.0.7 on 2026-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(db_column='MustChangePassword', default=True),
        ),
    ]