# Generated by Django 6.0.7 on 2026-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_shift_break_end_shift_break_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(blank=True, db_column='Rating', decimal_places=2, max_digits=3, null=True),
        ),
    ]
