# Generated by Django 6.0.7 on 2026-08-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
    ]
