# Generated by Django 6.0.7 on 2026-08-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_paused',
            field=models.BooleanField(db_column='IsPaused', default=False),
        ),
    ]
