# Generated by Django 6.0.7 on 2026-08-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_is_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_paused',
        ),
    ]
