# Generated by Django 6.0.7 on 2026-08-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_is_paused'),
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='org',
            field=models.ForeignKey(blank=True, db_column='OrgId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organizations.organization'),
        ),
    ]
