# Generated by Django 6.0.7 on 2026-09-16 07:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_shift_duration_hours_decimal'),
        ('organizations', '0004_organization_pan_number_organization_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_column='Email', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('org'), name='uniq_employee_email_per_org'),
        ),
    ]
