# Generated by Django 6.0.7 on 2026-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
