# Generated by Django 6.0.7 on 2026-09-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeservice',
            table='employeeservices',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shift',
        ),
    ]
