# Generated by Django 6.0.7 on 2026-08-03 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_mobile_alter_organization_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('CreatedBy', models.CharField(max_length=100)),
                ('CreatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, db_column='OrganizationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
            ],
            options={
                'db_table': 'customers',
                'constraints': [models.UniqueConstraint(fields=('organization', 'Mobile'), name='unique_customer_mobile_per_org')],
            },
        ),
    ]
